version: "3.7"
services:
  mailer-service:
    build:
      context: .
      target: development
    container_name: mailer-service
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - microservices
networks:
  microservices:
    external: true
