GET {{host}}/users

###

POST {{host}}/users
Content-Type: application/json

{
  "id": "6488a2bb-9c25-486a-addb-349b3056f695",
  "name": "Victor Miranda",
  "email": "vmmelo1@gmail.com",
  "password": 123456
}

###

GET {{host}}/users/6488a2bb-9c25-486a-addb-349b3056f695

###

PUT {{host}}/users/6488a2bb-9c25-486a-addb-349b3056f695
Content-Type: application/json

{
  "name": "Victor Miranda de Melo"
}

###

DELETE {{host}}/users/6488a2bb-9c25-486a-addb-349b3056f695

###


PATCH {{host}}/users/restore/6488a2bb-9c25-486a-addb-349b3056f695

###
