apiVersion: v1
kind: Pod
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  containers:
    - name: mailer-container
      image: vmmelo1/authenticator-mailer-ms:latest
      envFrom:
        - configMapRef:
            name: mailer-configmap