apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq-container
      image: rabbitmq:management-alpine
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: rabbitmq-configmap