apiVersion: v1
kind: Service
metadata:
  name: svc-rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      name: rabbitmq
    - port: 15672
      nodePort: 30001
      name: rabbitmq-management
  selector:
    app: rabbitmq