apiVersion: v1
kind: Pod
metadata:
  name: users
  labels:
    app: users
spec:
  containers:
    - name: users-container
      image: vmmelo1/authenticator-users-ms:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: users-configmap